version: '3'

services:
  #  painel:
  #    build:
  #      context: .
  #      dockerfile: dockerfile
  #    ports:
  #      - 8000:8000
  
  socket:
    build:
      context: .
      dockerfile: dockerfile_socket
    ports:
      - 8100:8100

  socket2:
    build:
      context: .
      dockerfile: dockerfile_socket
    ports:
      - 8101:8100
