version: '3'

services:
  painel:
    container_name: painel
    build:
      context: .
      dockerfile: dockerfile_frontend
    ports:
      - 8000:8000
  
  socket:
    container_name: socket
    build:
      context: .
      dockerfile: dockerfile_socket
    ports:
      - 8100:8100
