name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build painel chamada
      working-directory: ./painel/frontend
      run: npm run build
    - name: Iniciando docker
      run: docker-compose up -d
    
    
        
