name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 16
    - run: git branch
    - run: docker-compose up -d
